export const GET_OUTPUTTYPE_LIST_REQUEST = "GET_OUTPUTTYPE_LIST_REQUEST";
export const GET_OUTPUTTYPE_LIST_SUCCESS = "GET_OUTPUTTYPE_LIST_SUCCESS";
export const GET_OUTPUTTYPE_LIST_FAILED = "GET_OUTPUTTYPE_LIST_FAILED";

export const GET_KRABYDEPARTMENT_REQUEST = "GET_KRABYDEPARTMENT_REQUEST";
export const GET_KRABYDEPARTMENT_SUCCESS = "GET_KRABYDEPARTMENT_SUCCESS";
export const GET_KRABYDEPARTMENT_FAILED = "GET_KRABYDEPARTMENT_FAILED";

export const GET_PROJECTBYKRA_REQUEST = "GET_PROJECTBYKRA_REQUEST";
export const GET_PROJECTBYKRA_SUCCESS = "GET_PROJECTBYKRA_SUCCESS";
export const GET_PROJECTBYKRA_FAILED = "GET_PROJECTBYKRA_FAILED";

export const GET_PROJECTBYDEPARTMENT_REQUEST = "GET_PROJECTBYDEPARTMENT_REQUEST";
export const GET_PROJECTBYDEPARTMENT_SUCCESS = "GET_PROJECTBYDEPARTMENT_SUCCESS";
export const GET_PROJECTBYDEPARTMENT_FAILED = "GET_PROJECTBYDEPARTMENT_FAILED";

export const GET_DEPARTMENTLIST_REQUEST = "GET_DEPARTMENTLIST_REQUEST";
export const GET_DEPARTMENTLIST_SUCCESS = "GET_DEPARTMENTLIST_SUCCESS";
export const GET_DEPARTMENTLIST_FAILED = "GET_DEPARTMENTLIST_FAILED";

export const GET_OUTCOMETYPE_LIST_REQUEST = "GET_OUTCOMETYPE_LIST_REQUEST";
export const GET_OUTCOMETYPE_LIST_SUCCESS = "GET_OUTCOMETYPE_LIST_SUCCESS";
export const GET_OUTCOMETYPE_LIST_FAILED = "GET_OUTCOMETYPE_LIST_FAILED";

export const GET_UNITBYDEPARTMENT_REQUEST = "GET_UNITBYDEPARTMENT_REQUEST";
export const GET_UNITBYDEPARTMENT_SUCCESS = "GET_UNITBYDEPARTMENT_SUCCESS";
export const GET_UNITBYDEPARTMENT_FAILED = "GET_UNITBYDEPARTMENT_FAILED";

export const CLOSE_ALERT = "CLOSE_ALERT";
export const OPEN_ALERT = "OPEN_ALERT";