export const LIST_BUSINESSUNIT_REQUEST = "LIST_BUSINESSUNIT_REQUEST";
export const LIST_BUSINESSUNIT_SUCCESS = "LIST_BUSINESSUNIT_SUCCESS";
export const LIST_BUSINESSUNIT_FAILED = "LIST_BUSINESSUNIT_FAILED";

export const GET_BU_DEPLOYMENTS_REQUEST = "GET_BU_DEPLOYMENTS_REQUEST";
export const GET_BU_DEPLOYMENTS_SUCCESS = "GET_BU_DEPLOYMENTS_SUCCESS";
export const GET_BU_DEPLOYMENTS_FAILED = "GET_BU_DEPLOYMENTS_FAILED";

export const GET_MOST_DEPLOYED_REQUEST = "GET_MOST_DEPLOYED_REQUEST";
export const GET_MOST_DEPLOYED_SUCCESS = "GET_MOST_DEPLOYED_SUCCESS";
export const GET_MOST_DEPLOYED_FAILED = "GET_MOST_DEPLOYED_FAILED";