export const GET_OUTPUTTYPE_LIST_REQUEST = "GET_OUTPUTTYPE_LIST_REQUEST";
export const GET_OUTPUTTYPE_LIST_SUCCESS = "GET_OUTPUTTYPE_LIST_SUCCESS";
export const GET_OUTPUTTYPE_LIST_FAILED = "GET_OUTPUTTYPE_LIST_FAILED";

export const GET_KRABYDEPARTMENT_REQUEST = "GET_KRABYDEPARTMENT_REQUEST";
export const GET_KRABYDEPARTMENT_SUCCESS = "GET_KRABYDEPARTMENT_SUCCESS";
export const GET_KRABYDEPARTMENT_FAILED = "GET_KRABYDEPARTMENT_FAILED";

export const GET_PROJECTBYKRA_REQUEST = "GET_PROJECTBYKRA_REQUEST";
export const GET_PROJECTBYKRA_SUCCESS = "GET_PROJECTBYKRA_SUCCESS";
export const GET_PROJECTBYKRA_FAILED = "GET_PROJECTBYKRA_FAILED";