export const BAPI_GET_DETAILS_REQUEST = 'BAPI_GET_DETAILS_REQUEST';
export const BAPI_GET_DETAILS_SUCCESS = 'BAPI_GET_DETAILS_SUCCESS';
export const BAPI_GET_DETAILS_FAIL = 'BAPI_GET_DETAILS_FAIL';

export const BAPI_UPDATE_REQUEST = 'BAPI_UPDATE_REQUEST';
export const BAPI_UPDATE_SUCCESS = 'BAPI_UPDATE_SUCCESS';
export const BAPI_UPDATE_FAIL = 'BAPI_UPDATE_FAIL';

export const BAPI_DELETE_REQUEST = 'BAPI_DELETE_REQUEST';
export const BAPI_DELETE_SUCCESS = 'BAPI_DELETE_SUCCESS';
export const BAPI_DELETE_FAIL = 'BAPI_DELETE_FAIL';

export const BAPI_ADD_REQUEST = 'BAPI_ADD_REQUEST';
export const BAPI_ADD_SUCCESS = 'BAPI_ADD_SUCCESS';
export const BAPI_ADD_FAIL = 'BAPI_ADD_FAIL';

export const BAPI_GET_BUS_REQUEST = 'BAPI_GET_BUS_REQUEST';
export const BAPI_GET_BUS_SUCCESS = 'BAPI_GET_BUS_SUCCESS';
export const BAPI_GET_BUS_FAIL = 'BAPI_GET_BUS_FAIL';

export const BAPI_GET_INTERFACES_REQUEST = 'BAPI_GET_INTERFACES_REQUEST';
export const BAPI_GET_INTERFACES_SUCCESS = 'BAPI_GET_INTERFACES_SUCCESS';
export const BAPI_GET_INTERFACES_FAIL = 'BAPI_GET_INTERFACES_FAIL';
