export const GET_MONITOREDPPA_REQUEST = "GET_MONITOREDPPA_REQUEST";
export const GET_MONITOREDPPA_SUCCESS = "GET_MONITOREDPPA_SUCCESS";
export const GET_MONITOREDPPA_FAILED = "GET_MONITOREDPPA_FAILED";

export const GET_CONDUCTEDWITHINTIMEFRAME_REQUEST = "GET_CONDUCTEDWITHINTIMEFRAME_REQUEST";
export const GET_CONDUCTEDWITHINTIMEFRAME_SUCCESS = "GET_CONDUCTEDWITHINTIMEFRAME_SUCCESS";
export const GET_CONDUCTEDWITHINTIMEFRAME_FAILED = "GET_CONDUCTEDWITHINTIMEFRAME_FAILED";

export const GET_BudgetUtilizationRate_REQUEST = "GET_BudgetUtilizationRate_REQUEST";
export const GET_BudgetUtilizationRate_SUCCESS = "GET_BudgetUtilizationRate_SUCCESS";
export const GET_BudgetUtilizationRate_FAILED = "GET_BudgetUtilizationRate_FAILED";