export const GET_MONITOREDPPA_REQUEST = "GET_MONITOREDPPA_REQUEST";
export const GET_MONITOREDPPA_SUCCESS = "GET_MONITOREDPPA_SUCCESS";
export const GET_MONITOREDPPA_FAILED = "GET_MONITOREDPPA_FAILED";