export const SVN_INFO_REQUEST = "SVN_INFO_REQUEST";
export const SVN_INFO_SUCCESS = "SVN_INFO_SUCCESS";
export const SVN_INFO_FAILED = "SVN_INFO_FAILED";

export const SEARCH_INTERFACE_REQUEST = "SEARCH_INTERFACE_REQUEST";
export const SEARCH_INTERFACE_SUCCESS = "SEARCH_INTERFACE_SUCCESS";
export const SEARCH_INTERFACE_FAILED = "SEARCH_INTERFACE_FAILED";

export const SEARCH_BAPI_BY_INTERFACE_REQUEST = "SEARCH_BAPI_BY_INTERFACE_REQUEST";
export const SEARCH_BAPI_BY_INTERFACE_SUCCESS = "SEARCH_BAPI_BY_INTERFACE_SUCCESS";
export const SEARCH_BAPI_BY_INTERFACE_FAILED = "SEARCH_BAPI_BY_INTERFACE_FAILED";

export const INSERT_INTERFACE_REQUEST = "INSERT_INTERFACE_REQUEST";
export const INSERT_INTERFACE_SUCCESS = "INSERT_INTERFACE_SUCCESS";
export const INSERT_INTERFACE_FAILED = "INSERT_INTERFACE_FAILED";

export const EDIT_INTERFACE_REQUEST = "EDIT_INTERFACE_REQUEST";
export const EDIT_INTERFACE_SUCCESS = "EDIT_INTERFACE_SUCCESS";
export const EDIT_INTERFACE_FAILED = "EDIT_INTERFACE_FAILED";

export const DELETE_INTERFACE_REQUEST = "DELETE_INTERFACE_REQUEST";
export const DELETE_INTERFACE_SUCCESS = "DELETE_INTERFACE_SUCCESS";
export const DELETE_INTERFACE_FAILED = "DELETE_INTERFACE_FAILED";

export const INSERT_TASK_REQUEST = "INSERT_TASK_REQUEST";
export const INSERT_TASK_SUCCESS = "INSERT_TASK_SUCCESS";
export const INSERT_TASK_FAILED = "INSERT_TASK_FAILED";

export const DELETE_MULTIPLEINTERFACE_REQUEST = "DELETE_MULTIPLEINTERFACE_REQUEST";
export const DELETE_MULTIPLEINTERFACE_SUCCESS = "DELETE_MULTIPLEINTERFACE_SUCCESS";
export const DELETE_MULTIPLEINTERFACE_FAILED = "DELETE_MULTIPLEINTERFACE_FAILED";