export const SEARCH_KRA_REQUEST = "SEARCH_KRA_REQUEST";
export const SEARCH_KRA_OUTPUT_SUCCESS = "SEARCH_KRA_OUTPUT_SUCCESS";
export const SEARCH_KRA_OUTPUT_FAILED = "SEARCH_KRA_OUTPUT_FAILED";

export const ADD_KRA_OUTPUT_REQUEST = "ADD_KRA_OUTPUT_REQUEST";
export const ADD_KRA_OUTPUT_SUCCESS = "ADD_KRA_OUTPUT_SUCCESS";
export const ADD_KRA_OUTPUT_FAILED = "ADD_KRA_OUTPUT_FAILED";

export const EDIT_KRA_OUTPUT_REQUEST = "EDIT_KRA_OUTPUT_REQUEST";
export const EDIT_KRA_OUTPUT_SUCCESS = "EDIT_KRA_OUTPUT_SUCCESS";
export const EDIT_KRA_OUTPUT_FAILED = "EDIT_KRA_OUTPUT_FAILED";

