export const INSERT_OPEX_RECORD_REQUEST = "INSERT_OPEX_RECORD_REQUEST";
export const INSERT_OPEX_RECORD_SUCCESS = "INSERT_OPEX_RECORD_SUCCESS";
export const INSERT_OPEX_RECORD_FAILED = "INSERT_OPEX_RECORD_FAILED";

export const SEARCH_OPEX_RECORD_REQUEST  = "SEARCH_OPEX_RECORD_REQUEST";
export const SEARCH_OPEX_RECORD_SUCCESS  = "SEARCH_OPEX_RECORD_SUCCESS";
export const SEARCH_OPEX_RECORD_FAILED  = "SEARCH_OPEX_RECORD_FAILED";

