export const GET_LIST_OUTCOMETYPE_REQUEST = "GET_LIST_OUTCOMETYPE_REQUEST";
export const GET_LIST_OUTCOMETYPE_SUCCESS = "GET_LIST_OUTCOMETYPE_SUCCESS";
export const GET_LIST_OUTCOMETYPE_FAILED = "GET_LIST_OUTCOMETYPE_FAILED";

export const SEARCH_OUTCOME_REQUEST = "SEARCH_OUTCOME_REQUEST";
export const SEARCH_OUTCOME_SUCCESS = "SEARCH_OUTCOME_SUCCESS";
export const SEARCH_OUTCOME_FAILED = "SEARCH_OUTCOME_FAILED";

export const INSERT_OUTCOME_REQUEST = "INSERT_OUTCOME_REQUEST";
export const INSERT_OUTCOME_SUCCESS = "INSERT_OUTCOME_SUCCESS";
export const INSERT_OUTCOME_FAILED = "INSERT_OUTCOME_FAILED";