export const INSERT_MAJOR_OUTPUT_REQUEST = "INSERT_MAJOR_OUTPUT_REQUEST";
export const INSERT_MAJOR_OUTPUT_SUCCESS = "INSERT_MAJOR_OUTPUT_SUCCESS";
export const INSERT_MAJOR_OUTPUT_FAILED = "INSERT_MAJOR_OUTPUT_FAILED";

export const EDIT_MAJOR_OUTPUT_REQUEST = "EDIT_MAJOR_OUTPUT_REQUEST";
export const EDIT_MAJOR_OUTPUT_SUCCESS = "EDIT_MAJOR_OUTPUT_SUCCESS";
export const EDIT_MAJOR_OUTPUT_FAILED = "EDIT_MAJOR_OUTPUT_FAILED";

export const INSERT_MINOR_OUTPUT_REQUEST = "INSERT_MINOR_OUTPUT_REQUEST";
export const INSERT_MINOR_OUTPUT_SUCCESS = "INSERT_MINOR_OUTPUT_SUCCESS";
export const INSERT_MINOR_OUTPUT_FAILED = "INSERT_MINOR_OUTPUT_FAILED";

export const EDIT_MINOR_OUTPUT_REQUEST = "EDIT_MINOR_OUTPUT_REQUEST";
export const EDIT_MINOR_OUTPUT_SUCCESS = "EDIT_MINOR_OUTPUT_SUCCESS";
export const EDIT_MINOR_OUTPUT_FAILED = "EDIT_MINOR_OUTPUT_FAILED";

export const INSERT_CONTRIBUTORY_OUTPUT_REQUEST = "INSERT_CONTRIBUTORY_OUTPUT_REQUEST";
export const INSERT_CONTRIBUTORY_OUTPUT_SUCCESS = "INSERT_CONTRIBUTORY_OUTPUT_SUCCESS";
export const INSERT_CONTRIBUTORY_OUTPUT_FAILED = "INSERT_CONTRIBUTORY_OUTPUT_FAILED";

export const SEARCH_CONTRIBUTORY_OUTPUT_REQUEST = "SEARCH_CONTRIBUTORY_OUTPUT_REQUEST";
export const SEARCH_CONTRIBUTORY_OUTPUT_SUCCESS = "SEARCH_CONTRIBUTORY_OUTPUT_SUCCESS";
export const SEARCH_CONTRIBUTORY_OUTPUT_FAILED = "SEARCH_CONTRIBUTORY_OUTPUT_FAILED";

export const SEARCH_MAJOR_OUTPUT_REQUEST = "SEARCH_MAJOR_OUTPUT_REQUEST";
export const SEARCH_MAJOR_OUTPUT_SUCCESS = "SEARCH_MAJOR_OUTPUT_SUCCESS";
export const SEARCH_MAJOR_OUTPUT_FAILED = "SEARCH_MAJOR_OUTPUT_FAILED";

export const SEARCH_MINOR_OUTPUT_REQUEST = "SEARCH_MINOR_OUTPUT_REQUEST";
export const SEARCH_MINOR_OUTPUT_SUCCESS = "SEARCH_MINOR_OUTPUT_SUCCESS";
export const SEARCH_MINOR_OUTPUT_FAILED = "SEARCH_MINOR_OUTPUT_FAILED";

export const LIST_INDICATORSBYDEPT_REQUEST = "LIST_INDICATORSBYDEPT_REQUEST";
export const LIST_INDICATORSBYDEPT_SUCCESS = "LIST_INDICATORSBYDEPT_SUCCESS";
export const LIST_INDICATORSBYDEPT_FAILED = "LIST_INDICATORSBYDEPT_FAILED";

export const EDIT_OUTPUTSTATUS_REQUEST = "EDIT_OUTPUTSTATUS_REQUEST";
export const EDIT_OUTPUTSTATUS_SUCCESS = "EDIT_OUTPUTSTATUS_SUCCESS";
export const EDIT_OUTPUTSTATUS_FAILED = "EDIT_OUTPUTSTATUS_FAILED";

export const GET_TARGETBYOUTPUTID_REQUEST = "GET_TARGETBYOUTPUTID_REQUEST";
export const GET_TARGETBYOUTPUTID_SUCCESS = "GET_TARGETBYOUTPUTID_SUCCESS";
export const GET_TARGETBYOUTPUTID_FAILED = "GET_TARGETBYOUTPUTID_FAILED";

export const DELETE_TARGETBYID_REQUEST = "DELETE_TARGETBYID_REQUEST";
export const DELETE_TARGETBYID_SUCCESS = "DELETE_TARGETBYID_SUCCESS";
export const DELETE_TARGETBYID_FAILED = "DELETE_TARGETBYID_FAILED";