export const INSERT_MAJOR_OUTPUT_REQUEST = "INSERT_MAJOR_OUTPUT_REQUEST";
export const INSERT_MAJOR_OUTPUT_SUCCESS = "INSERT_MAJOR_OUTPUT_SUCCESS";
export const INSERT_MAJOR_OUTPUT_FAILED = "INSERT_MAJOR_OUTPUT_FAILED";

export const INSERT_MINOR_OUTPUT_REQUEST = "INSERT_MINOR_OUTPUT_REQUEST";
export const INSERT_MINOR_OUTPUT_SUCCESS = "INSERT_MINOR_OUTPUT_SUCCESS";
export const INSERT_MINOR_OUTPUT_FAILED = "INSERT_MINOR_OUTPUT_FAILED";

export const INSERT_CONTRIBUTORY_OUTPUT_REQUEST = "INSERT_CONTRIBUTORY_OUTPUT_REQUEST";
export const INSERT_CONTRIBUTORY_OUTPUT_SUCCESS = "INSERT_CONTRIBUTORY_OUTPUT_SUCCESS";
export const INSERT_CONTRIBUTORY_OUTPUT_FAILED = "INSERT_CONTRIBUTORY_OUTPUT_FAILED";

export const SEARCH_MAJOR_OUTPUT_REQUEST = "SEARCH_MAJOR_OUTPUT_REQUEST";
export const SEARCH_MAJOR_OUTPUT_SUCCESS = "SEARCH_MAJOR_OUTPUT_SUCCESS";
export const SEARCH_MAJOR_OUTPUT_FAILED = "SEARCH_MAJOR_OUTPUT_FAILED";

export const LIST_INDICATORSBYDEPT_REQUEST = "LIST_INDICATORSBYDEPT_REQUEST";
export const LIST_INDICATORSBYDEPT_SUCCESS = "LIST_INDICATORSBYDEPT_SUCCESS";
export const LIST_INDICATORSBYDEPT_FAILED = "LIST_INDICATORSBYDEPT_FAILED";