export const INSERT_MAJOR_OUTPUT_REQUEST = "INSERT_MAJOR_OUTPUT_REQUEST";
export const INSERT_MAJOR_OUTPUT_SUCCESS = "INSERT_MAJOR_OUTPUT_SUCCESS";
export const INSERT_MAJOR_OUTPUT_FAILED = "INSERT_MAJOR_OUTPUT_FAILED";

export const INSERT_MINOR_OUTPUT_REQUEST = "INSERT_MINOR_OUTPUT_REQUEST";
export const INSERT_MINOR_OUTPUT_SUCCESS = "INSERT_MINOR_OUTPUT_SUCCESS";
export const INSERT_MINOR_OUTPUT_FAILED = "INSERT_MINOR_OUTPUT_FAILED";