export const SEARCH_PREXC_REQUEST = "SEARCH_PREXC_REQUEST";
export const SEARCH_PREXC_SUCCESS = "SEARCH_PREXC_SUCCESS";
export const SEARCH_PREXC_FAILED = "SEARCH_PREXC_FAILED";

export const INSERT_PREXC_REQUEST = "INSERT_PREXC_REQUEST";
export const INSERT_PREXC_SUCCESS = "INSERT_PREXC_SUCCESS";
export const INSERT_PREXC_FAILED = "INSERT_PREXC_FAILED";

export const LIST_ORGOUTCOME_REQUEST = "LIST_ORGOUTCOME_REQUEST";
export const LIST_ORGOUTCOME_SUCCESS = "LIST_ORGOUTCOME_SUCCESS";
export const LIST_ORGOUTCOME_FAILED = "LIST_ORGOUTCOME_FAILED";

export const INSERT_ORGOUTCOME_REQUEST = "INSERT_ORGOUTCOME_REQUEST";
export const INSERT_ORGOUTCOME_SUCCESS = "INSERT_ORGOUTCOME_SUCCESS";
export const INSERT_ORGOUTCOME_FAILED = "INSERT_ORGOUTCOMER_FAILED";

export const INSERT_PREXCPROJECT_REQUEST = "INSERT_PROJECT_REQUEST";
export const INSERT_PREXCPROJECT_SUCCESS = "INSERT_PREXCPROJECT_SUCCESS";
export const INSERT_PREXCPROJECT_FAILED = "INSERT_PREXCPROJECT_FAILED";

export const INSERT_PREXCINDICATOR_REQUEST = "INSERT_INDICATOR_REQUEST";
export const INSERT_PREXCINDICATOR_SUCCESS = "INSERT_INDICATOR_SUCCESS";
export const INSERT_PREXCINDICATOR_FAILED = "INSERT_INDICATOR_FAILED";

export const LIST_PROJECTINDICATORS_REQUEST = "LIST_PROJECTINDICATORS_REQUEST";
export const LIST_PROJECTINDICATORS_SUCCESS = "LIST_PROJECTINDICATORS_SUCCESS";
export const LIST_PROJECTINDICATORS_FAILED = "LIST_PROJECTINDICATORS_FAILED";

export const EDIT_INDICATORVALUE_REQUEST = "EDIT_INDICATORVALUE_REQUEST";
export const EDIT_INDICATORVALUE_SUCCESS = "EDIT_INDICATORVALUE_SUCCESS";
export const EDIT_INDICATORVALUE_FAILED = "EDIT_INDICATORVALUE_FAILED";

export const SEARCH_INDICATORVALUE_REQUEST = "SEARCH_INDICATORVALUE_REQUEST";
export const SEARCH_INDICATORVALUE_SUCCESS = "SEARCH_INDICATORVALUE_SUCCESS";
export const SEARCH_INDICATORVALUE_FAILED = "SEARCH_INDICATORVALUE_FAILED";

export const UPDATE_INDICATORVALUESTATUS_REQUEST = "UPDATE_INDICATORVALUESTATUS_REQUEST";
export const UPDATE_INDICATORVALUESTATUS_SUCCESS = "UPDATE_INDICATORVALUESTATUS_SUCCESS";
export const UPDATE_INDICATORVALUESTATUS_FAILED = "UPDATE_INDICATORVALUESTATUS_FAILED";