export const SEARCH_PREXC_REQUEST = "SEARCH_PREXC_REQUEST";
export const SEARCH_PREXC_SUCCESS = "SEARCH_PREXC_SUCCESS";
export const SEARCH_PREXC_FAILED = "SEARCH_PREXC_FAILED";

export const INSERT_PREXC_REQUEST = "INSERT_PREXC_REQUEST";
export const INSERT_PREXC_SUCCESS = "INSERT_PREXC_SUCCESS";
export const INSERT_PREXC_FAILED = "INSERT_PREXC_FAILED";

export const LIST_ORGOUTCOME_REQUEST = "LIST_ORGOUTCOME_REQUEST";
export const LIST_ORGOUTCOME_SUCCESS = "LIST_ORGOUTCOME_SUCCESS";
export const LIST_ORGOUTCOME_FAILED = "LIST_ORGOUTCOME_FAILED";

export const INSERT_ORGOUTCOME_REQUEST = "INSERT_ORGOUTCOME_REQUEST";
export const INSERT_ORGOUTCOME_SUCCESS = "INSERT_ORGOUTCOME_SUCCESS";
export const INSERT_ORGOUTCOME_FAILED = "INSERT_ORGOUTCOMER_FAILED";

export const INSERT_PREXCPROJECT_REQUEST = "INSERT_PROJECT_REQUEST";
export const INSERT_PREXCPROJECT_SUCCESS = "INSERT_PREXCPROJECT_SUCCESS";
export const INSERT_PREXCPROJECT_FAILED = "INSERT_PREXCPROJECT_FAILED";