export const SEARCH_PROJECT_OUTPUT_REQUEST = "SEARCH_PROJECT_OUTPUT_REQUEST";
export const SEARCH_PROJECT_OUTPUT_SUCCESS = "SEARCH_PROJECT_OUTPUT_SUCCESS";
export const SEARCH_PROJECT_OUTPUT_FAILED = "SEARCH_PROJECT_OUTPUT_FAILED";

export const ADD_PROJECT_OUTPUT_REQUEST = "ADD_PROJECT_OUTPUT_REQUEST";
export const ADD_PROJECT_OUTPUT_SUCCESS = "ADD_PROJECT_OUTPUT_SUCCESS";
export const ADD_PROJECT_OUTPUT_FAILED = "ADD_PROJECT_OUTPUT_FAILED";

export const EDIT_PROJECT_OUTPUT_REQUEST = "EDIT_PROJECT_OUTPUT_REQUEST";
export const EDIT_PROJECT_OUTPUT_SUCCESS = "EDIT_PROJECT_OUTPUT_SUCCESS";
export const EDIT_PROJECT_OUTPUT_FAILED = "EDIT_PROJECT_OUTPUT_FAILED";

