export const SEARCH_USER_ROLE_REQUEST = "SEARCH_USER_ROLE_REQUEST";
export const SEARCH_USER_ROLE_SUCCESS = "SEARCH_USER_ROLE_SUCCESS";
export const SEARCH_USER_ROLE_FAILED = "SEARCH_USER_ROLE_FAILED";

export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILED = "GET_ROLES_FAILED";

export const GET_ACTIONS_REQUEST = "GET_ACTIONS_REQUEST";
export const GET_ACTIONS_SUCCESS = "GET_ACTIONS_SUCCESS";
export const GET_ACTIONS_FAILED = "GET_ACTIONS_FAILED";

export const GET_ROLES_LIST_REQUEST = "GET_ROLES_LIST_REQUEST";
export const GET_ROLES_LIST_SUCCESS = "GET_ROLES_LIST_SUCCESS";
export const GET_ROLES_LIST_FAILED = "GET_ROLES_LIST_FAILED";

export const INSERT_ROLEACTION_REQUEST = "INSERT_ROLEACTION_REQUEST";
export const INSERT_ROLEACTION_SUCCESS = "INSERT_ROLEACTION_SUCCESS";
export const INSERT_ROLEACTION_FAILED = "INSERT_ROLEACTION_FAILED";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";

export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAILED = "CREATE_ROLE_FAILED";