export const GET_TICKET_BY_INTERFACE_REQUEST = "GET_TICKET_BY_INTERFACE_REQUEST";
export const GET_TICKET_BY_INTERFACE_SUCCESS = "GET_TICKET_BY_INTERFACE_SUCCESS";
export const GET_TICKET_BY_INTERFACE_FAILED = "GET_TICKET_BY_INTERFACE_FAILED";

export const LIST_TICKETTYPES_REQUEST = "LIST_TICKETTYPES_REQUEST";
export const LIST_TICKETTYPES_SUCCESS = "LIST_TICKETTYPES_SUCCESS";
export const LIST_TICKETTYPES_FAILED = "LIST_TICKETTYPES_FAILED";